version: '3'

services:
  app-production:
    image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
    container_name: app-production
    env_file: .env
    networks: 
      - nginx
    restart: always
networks:
  nginx:
    external: true
