version: '3'

services:
  app-staging:
    build: 
      context: .
    container_name: app-staging
    env_file: .env
    networks: 
      - nginx
    restart: always

networks:
  nginx:
    external: true
